### ISSUE TITLE
Error during import:  /snap/nextcloud/28088/bin/import-data: 62: /snap/nextcloud/28088/bin/import-data: cannot open /var/snap/nextcloud/current/nextcloudbackup/database.sql: No such file

### ISSUE THREAD

**Issue by THEWHITEBOY503** [nextcloud-snap/nextcloud-snap#1773]
I'm trying to import from a nextcloud snap backup, but I get this error:
```Clearing existing non-default apps... done
Importing apps...
        442.53M 100%   57.82MB/s    0:00:07 (xfr#22738, to-chk=0/25710)
Dropping existing database... done
Creating new database... done
Granting database privileges to existing user... done
Importing database...
/snap/nextcloud/28088/bin/import-data: 62: /snap/nextcloud/28088/bin/import-data: cannot open /var/snap/nextcloud/current/nextcloudbackup/database.sql: No such file
Unable to import database
Disabling maintenance mode... error
An unhandled exception has been thrown:
PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_appconfig' doesn't exist in /snap/nextcloud/28088/htdocs/3rdparty/doctrine/dbal/src/Driver/PDO/Connection.php:82
Stack trace:
#0 /snap/nextcloud/28088/htdocs/3rdparty/doctrine/dbal/src/Driver/PDO/Connection.php(82): PDO->query('SELECT * FROM `...')
#1 /snap/nextcloud/28088/htdocs/3rdparty/doctrine/dbal/src/Connection.php(1035): Doctrine\DBAL\Driver\PDO\Connection->query('SELECT * FROM `...')
#2 /snap/nextcloud/28088/htdocs/lib/private/DB/Connection.php(226): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM `...', Array, Array, NULL)
#3 /snap/nextcloud/28088/htdocs/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php(210): OC\DB\Connection->executeQuery('SELECT * FROM `...', Array, Array)
#4 /snap/nextcloud/28088/htdocs/lib/private/DB/QueryBuilder/QueryBuilder.php(287): Doctrine\DBAL\Query\QueryBuilder->execute()
#5 /snap/nextcloud/28088/htdocs/lib/private/AppConfig.php(345): OC\DB\QueryBuilder\QueryBuilder->execute()
#6 /snap/nextcloud/28088/htdocs/lib/private/AppConfig.php(110): OC\AppConfig->loadConfigValues()
#7 /snap/nextcloud/28088/htdocs/lib/private/AppConfig.php(301): OC\AppConfig->getApps()
#8 /snap/nextcloud/28088/htdocs/lib/private/legacy/OC_App.php(957): OC\AppConfig->getValues(false, 'installed_versi...')
#9 /snap/nextcloud/28088/htdocs/lib/private/Server.php(682): OC_App::getAppVersions()
#10 /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(155): OC\Server->OC\{closure}(Object(OC\Server))
#11 /snap/nextcloud/28088/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#12 /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(122): Pimple\Container->offsetGet('OC\Memcache\Fac...')
#13 /snap/nextcloud/28088/htdocs/lib/private/ServerContainer.php(137): OC\AppFramework\Utility\SimpleContainer->query('OC\Memcache\Fac...', false)
#14 /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\ServerContainer->query('OC\Memcache\Fac...')
#15 /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(177): OC\AppFramework\Utility\SimpleContainer->get('OC\Memcache\Fac...')
#16 /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(155): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#17 /snap/nextcloud/28088/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#18 /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(122): Pimple\Container->offsetGet('OCP\ICacheFacto...')
#19 /snap/nextcloud/28088/htdocs/lib/private/ServerContainer.php(137): OC\AppFramework\Utility\SimpleContainer->query('OCP\ICacheFacto...', false)
#20 /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\ServerContainer->query('OCP\ICacheFacto...')
#21 /snap/nextcloud/28088/htdocs/lib/private/Server.php(1031): OC\AppFramework\Utility\SimpleContainer->get('OCP\ICacheFacto...')
#22 /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(155): OC\Server->OC\{closure}(Object(OC\Server))
#23 /snap/nextcloud/28088/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#24 /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(122): Pimple\Container->offsetGet('OCP\Lock\ILocki...')
#25 /snap/nextcloud/28088/htdocs/lib/private/ServerContainer.php(137): OC\AppFramework\Utility\SimpleContainer->query('OCP\Lock\ILocki...', false)
#26 /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\ServerContainer->query('OCP\Lock\ILocki...')
#27 /snap/nextcloud/28088/htdocs/lib/private/Server.php(1990): OC\AppFramework\Utility\SimpleContainer->get('OCP\Lock\ILocki...')
#28 /snap/nextcloud/28088/htdocs/lib/private/Files/View.php(119): OC\Server->getLockingProvider()
#29 /snap/nextcloud/28088/htdocs/lib/private/Server.php(430): OC\Files\View->__construct()
#30 /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(155): OC\Server->OC\{closure}(Object(OC\Server))
#31 /snap/nextcloud/28088/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#32 /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(122): Pimple\Container->offsetGet('OC\Files\Node\H...')
#33 /snap/nextcloud/28088/htdocs/lib/private/ServerContainer.php(137): OC\AppFramework\Utility\SimpleContainer->query('OC\Files\Node\H...', false)
#34 /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\ServerContainer->query('OC\Files\Node\H...')
#35 /snap/nextcloud/28088/htdocs/lib/private/Server.php(1353): OC\AppFramework\Utility\SimpleContainer->get('OC\Files\Node\H...')
#36 /snap/nextcloud/28088/htdocs/lib/base.php(588): OC\Server->boot()
#37 /snap/nextcloud/28088/htdocs/lib/base.php(1076): OC::init()
#38 /snap/nextcloud/28088/htdocs/console.php(49): require_once('/snap/nextcloud...')
#39 /snap/nextcloud/28088/htdocs/occ(11): require_once('/snap/nextcloud...')
#40 {main}

Next Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_appconfig' doesn't exist in /snap/nextcloud/28088/htdocs/3rdparty/doctrine/dbal/src/Driver/PDO/Exception.php:26
Stack trace:
#0 /snap/nextcloud/28088/htdocs/3rdparty/doctrine/dbal/src/Driver/PDO/Connection.php(87): Doctrine\DBAL\Driver\PDO\Exception::new(Object(PDOException))
#1 /snap/nextcloud/28088/htdocs/3rdparty/doctrine/dbal/src/Connection.php(1035): Doctrine\DBAL\Driver\PDO\Connection->query('SELECT * FROM `...')
#2 /snap/nextcloud/28088/htdocs/lib/private/DB/Connection.php(226): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM `...', Array, Array, NULL)
#3 /snap/nextcloud/28088/htdocs/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php(210): OC\DB\Connection->executeQuery('SELECT * FROM `...', Array, Array)
#4 /snap/nextcloud/28088/htdocs/lib/private/DB/QueryBuilder/QueryBuilder.php(287): Doctrine\DBAL\Query\QueryBuilder->execute()
#5 /snap/nextcloud/28088/htdocs/lib/private/AppConfig.php(345): OC\DB\QueryBuilder\QueryBuilder->execute()
#6 /snap/nextcloud/28088/htdocs/lib/private/AppConfig.php(110): OC\AppConfig->loadConfigValues()
#7 /snap/nextcloud/28088/htdocs/lib/private/AppConfig.php(301): OC\AppConfig->getApps()
#8 /snap/nextcloud/28088/htdocs/lib/private/legacy/OC_App.php(957): OC\AppConfig->getValues(false, 'installed_versi...')
#9 /snap/nextcloud/28088/htdocs/lib/private/Server.php(682): OC_App::getAppVersions()
#10 /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(155): OC\Server->OC\{closure}(Object(OC\Server))
#11 /snap/nextcloud/28088/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#12 /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(122): Pimple\Container->offsetGet('OC\Memcache\Fac...')
#13 /snap/nextcloud/28088/htdocs/lib/private/ServerContainer.php(137): OC\AppFramework\Utility\SimpleContainer->query('OC\Memcache\Fac...', false)
#14 /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\ServerContainer->query('OC\Memcache\Fac...')
#15 /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(177): OC\AppFramework\Utility\SimpleContainer->get('OC\Memcache\Fac...')
#16 /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(155): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#17 /snap/nextcloud/28088/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#18 /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(122): Pimple\Container->offsetGet('OCP\ICacheFacto...')
#19 /snap/nextcloud/28088/htdocs/lib/private/ServerContainer.php(137): OC\AppFramework\Utility\SimpleContainer->query('OCP\ICacheFacto...', false)
#20 /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\ServerContainer->query('OCP\ICacheFacto...')
#21 /snap/nextcloud/28088/htdocs/lib/private/Server.php(1031): OC\AppFramework\Utility\SimpleContainer->get('OCP\ICacheFacto...')
#22 /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(155): OC\Server->OC\{closure}(Object(OC\Server))
#23 /snap/nextcloud/28088/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#24 /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(122): Pimple\Container->offsetGet('OCP\Lock\ILocki...')
#25 /snap/nextcloud/28088/htdocs/lib/private/ServerContainer.php(137): OC\AppFramework\Utility\SimpleContainer->query('OCP\Lock\ILocki...', false)
#26 /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\ServerContainer->query('OCP\Lock\ILocki...')
#27 /snap/nextcloud/28088/htdocs/lib/private/Server.php(1990): OC\AppFramework\Utility\SimpleContainer->get('OCP\Lock\ILocki...')
#28 /snap/nextcloud/28088/htdocs/lib/private/Files/View.php(119): OC\Server->getLockingProvider()
#29 /snap/nextcloud/28088/htdocs/lib/private/Server.php(430): OC\Files\View->__construct()
#30 /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(155): OC\Server->OC\{closure}(Object(OC\Server))
#31 /snap/nextcloud/28088/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#32 /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(122): Pimple\Container->offsetGet('OC\Files\Node\H...')
#33 /snap/nextcloud/28088/htdocs/lib/private/ServerContainer.php(137): OC\AppFramework\Utility\SimpleContainer->query('OC\Files\Node\H...', false)
#34 /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\ServerContainer->query('OC\Files\Node\H...')
#35 /snap/nextcloud/28088/htdocs/lib/private/Server.php(1353): OC\AppFramework\Utility\SimpleContainer->get('OC\Files\Node\H...')
#36 /snap/nextcloud/28088/htdocs/lib/base.php(588): OC\Server->boot()
#37 /snap/nextcloud/28088/htdocs/lib/base.php(1076): OC::init()
#38 /snap/nextcloud/28088/htdocs/console.php(49): require_once('/snap/nextcloud...')
#39 /snap/nextcloud/28088/htdocs/occ(11): require_once('/snap/nextcloud...')
#40 {main}

Next Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_appconfig' doesn't exist in /snap/nextcloud/28088/htdocs/3rdparty/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:47
Stack trace:
#0 /snap/nextcloud/28088/htdocs/3rdparty/doctrine/dbal/src/Connection.php(1728): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert(Object(Doctrine\DBAL\Driver\PDO\Exception), Object(Doctrine\DBAL\Query))
#1 /snap/nextcloud/28088/htdocs/3rdparty/doctrine/dbal/src/Connection.php(1667): Doctrine\DBAL\Connection->handleDriverException(Object(Doctrine\DBAL\Driver\PDO\Exception), Object(Doctrine\DBAL\Query))
#2 /snap/nextcloud/28088/htdocs/3rdparty/doctrine/dbal/src/Connection.php(1040): Doctrine\DBAL\Connection->convertExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDO\Exception), 'SELECT * FROM `...', Array, Array)
#3 /snap/nextcloud/28088/htdocs/lib/private/DB/Connection.php(226): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM `...', Array, Array, NULL)
#4 /snap/nextcloud/28088/htdocs/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php(210): OC\DB\Connection->executeQuery('SELECT * FROM `...', Array, Array)
#5 /snap/nextcloud/28088/htdocs/lib/private/DB/QueryBuilder/QueryBuilder.php(287): Doctrine\DBAL\Query\QueryBuilder->execute()
#6 /snap/nextcloud/28088/htdocs/lib/private/AppConfig.php(345): OC\DB\QueryBuilder\QueryBuilder->execute()
#7 /snap/nextcloud/28088/htdocs/lib/private/AppConfig.php(110): OC\AppConfig->loadConfigValues()
#8 /snap/nextcloud/28088/htdocs/lib/private/AppConfig.php(301): OC\AppConfig->getApps()
#9 /snap/nextcloud/28088/htdocs/lib/private/legacy/OC_App.php(957): OC\AppConfig->getValues(false, 'installed_versi...')
#10 /snap/nextcloud/28088/htdocs/lib/private/Server.php(682): OC_App::getAppVersions()
#11 /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(155): OC\Server->OC\{closure}(Object(OC\Server))
#12 /snap/nextcloud/28088/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#13 /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(122): Pimple\Container->offsetGet('OC\Memcache\Fac...')
#14 /snap/nextcloud/28088/htdocs/lib/private/ServerContainer.php(137): OC\AppFramework\Utility\SimpleContainer->query('OC\Memcache\Fac...', false)
#15 /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\ServerContainer->query('OC\Memcache\Fac...')
#16 /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(177): OC\AppFramework\Utility\SimpleContainer->get('OC\Memcache\Fac...')
#17 /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(155): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#18 /snap/nextcloud/28088/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#19 /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(122): Pimple\Container->offsetGet('OCP\ICacheFacto...')
#20 /snap/nextcloud/28088/htdocs/lib/private/ServerContainer.php(137): OC\AppFramework\Utility\SimpleContainer->query('OCP\ICacheFacto...', false)
#21 /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\ServerContainer->query('OCP\ICacheFacto...')
#22 /snap/nextcloud/28088/htdocs/lib/private/Server.php(1031): OC\AppFramework\Utility\SimpleContainer->get('OCP\ICacheFacto...')
#23 /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(155): OC\Server->OC\{closure}(Object(OC\Server))
#24 /snap/nextcloud/28088/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#25 /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(122): Pimple\Container->offsetGet('OCP\Lock\ILocki...')
#26 /snap/nextcloud/28088/htdocs/lib/private/ServerContainer.php(137): OC\AppFramework\Utility\SimpleContainer->query('OCP\Lock\ILocki...', false)
#27 /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\ServerContainer->query('OCP\Lock\ILocki...')
#28 /snap/nextcloud/28088/htdocs/lib/private/Server.php(1990): OC\AppFramework\Utility\SimpleContainer->get('OCP\Lock\ILocki...')
#29 /snap/nextcloud/28088/htdocs/lib/private/Files/View.php(119): OC\Server->getLockingProvider()
#30 /snap/nextcloud/28088/htdocs/lib/private/Server.php(430): OC\Files\View->__construct()
#31 /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(155): OC\Server->OC\{closure}(Object(OC\Server))
#32 /snap/nextcloud/28088/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#33 /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(122): Pimple\Container->offsetGet('OC\Files\Node\H...')
#34 /snap/nextcloud/28088/htdocs/lib/private/ServerContainer.php(137): OC\AppFramework\Utility\SimpleContainer->query('OC\Files\Node\H...', false)
#35 /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\ServerContainer->query('OC\Files\Node\H...')
#36 /snap/nextcloud/28088/htdocs/lib/private/Server.php(1353): OC\AppFramework\Utility\SimpleContainer->get('OC\Files\Node\H...')
#37 /snap/nextcloud/28088/htdocs/lib/base.php(588): OC\Server->boot()
#38 /snap/nextcloud/28088/htdocs/lib/base.php(1076): OC::init()
#39 /snap/nextcloud/28088/htdocs/console.php(49): require_once('/snap/nextcloud...')
#40 /snap/nextcloud/28088/htdocs/occ(11): require_once('/snap/nextcloud...')
#41 {main}
```
Any ideas?

**Comment by kyrofa** [comment]
What flags did you use to export the backup? Any chance it actually doesn't include the database?
