### ISSUE TITLE
snap/plugins/x-apache.py fails with KeyError when appending required attributes to 

### ISSUE THREAD

**Issue by r4co0n** [nextcloud-snap/nextcloud-snap#1892]
#### Describe the bug
Building the snap fails with:

```
Legacy plugin name detected, please rename the plugin's file name 'x-apache.py' to 'apache.py'.
Loaded local plugin for apache
'required'
We would appreciate it if you anonymously reported this issue.
No other data than the traceback and the version of snapcraft in use will be sent.
Would you like to send this error data? (Yes/No/Always/View) [no]: v
Traceback (most recent call last):
  File "/snap/snapcraft/6751/bin/snapcraft", line 33, in <module>
    sys.exit(load_entry_point('snapcraft==5.0', 'console_scripts', 'snapcraft')())
  File "/snap/snapcraft/6751/lib/python3.6/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/snap/snapcraft/6751/lib/python3.6/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/snap/snapcraft/6751/lib/python3.6/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/snap/snapcraft/6751/lib/python3.6/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/snapcraft/6751/lib/python3.6/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/snap/snapcraft/6751/lib/python3.6/site-packages/snapcraft/cli/lifecycle.py", line 387, in snap
    _execute(steps.PRIME, parts=tuple(), pack_project=True, output=output, **kwargs)
  File "/snap/snapcraft/6751/lib/python3.6/site-packages/snapcraft/cli/lifecycle.py", line 101, in _execute
    project_config = project_loader.load_config(project)
  File "/snap/snapcraft/6751/lib/python3.6/site-packages/snapcraft/internal/project_loader/__init__.py", line 34, in load_config
    return Config(project)
  File "/snap/snapcraft/6751/lib/python3.6/site-packages/snapcraft/internal/project_loader/_config.py", line 224, in __init__
    parts=self.data, project=project, validator=self.validator
  File "/snap/snapcraft/6751/lib/python3.6/site-packages/snapcraft/internal/project_loader/_parts_config.py", line 48, in __init__
    self._process_parts()
  File "/snap/snapcraft/6751/lib/python3.6/site-packages/snapcraft/internal/project_loader/_parts_config.py", line 67, in _process_parts
    self.load_part(part_name, plugin_name, properties)
  File "/snap/snapcraft/6751/lib/python3.6/site-packages/snapcraft/internal/project_loader/_parts_config.py", line 184, in load_part
    definitions_schema=self._validator.definitions_schema,
  File "/snap/snapcraft/6751/lib/python3.6/site-packages/snapcraft/internal/pluginhandler/_plugin_loader.py", line 58, in load_plugin
    plugin_schema = plugin_class.schema()
  File "/root/project/snap/plugins/x-apache.py", line 25, in schema
    schema['required'].append('modules')
KeyError: 'required'
We would appreciate it if you anonymously reported this issue.
[...]
```

We try to set a field in the schema dictionary which is undefined, which can be accomplished by some if/else:

```
diff --git a/snap/plugins/x-apache.py b/snap/plugins/x-apache.py
index ff08d62..93380cc 100644
--- a/snap/plugins/x-apache.py
+++ b/snap/plugins/x-apache.py
@@ -22,7 +22,10 @@ class ApachePlugin(snapcraft.BasePlugin):
             'default': 'event',
         }
 
-        schema['required'].append('modules')
+        if 'required' in schema:
+            schema['required'].append('modules')
+        else:
+            schema['required'] = ['modules']
 
         return schema
```

I will submit a PR soon, I hope to get the snap building again so I can do some real development. Please note that I previously patched snap/snapcraft.yaml to include:
```
diff --git a/snap/snapcraft.yaml b/snap/snapcraft.yaml
index 02e63f8..68c7ce2 100644
--- a/snap/snapcraft.yaml
+++ b/snap/snapcraft.yaml
@@ -1,4 +1,5 @@
 name: nextcloud
+base: core20
 version: 13.0.2snap1
 summary: Nextcloud Server - A safe home for all your data
 description: |
```

I am not sure if this is still necessary to build successfully and will report back if that's the case.

#### To Reproduce
1. Clone the repository , get some recent snapcraft and multipass
2. Run `snapcraft` in the repository directory

#### Expected behavior
A snap is built. Or regarding this error, the string 'modules' is added to requirements regardless of the key `requires` previously existing.

#### OS/snapd/snap version

    $ git rev-parse HEAD  # (On host system)
    dd090143d25ea16c7c1c09ebadbb46033a12bfa2

    $ snap info snapcraft | grep ^installed:  # (In multipass VM)
    installed:          5.0                                 (6751) 58MB classic

    # snap info multipass | grep ^installed:  # (In my build-wrapper VM)
    installed:          1.7.1                              (5317) 326MB -

    # uname -ar  # (In multipass VM)
    Linux snapcraft-nextcloud 5.4.0-84-generic #94-Ubuntu SMP Thu Aug 26 20:27:37 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

    # uname -ar  # (In my build-wrapper VM)
    # uname -ar
    Linux ubuntu-focal 5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by r4co0n** [comment]
f, it seems I was still using a revision from June, I can trick myself with multiple remotes once a year, as is tradition.
