### ISSUE TITLE
Internal server error + broken redis after trying to move Nextcloud data folder to external storage

### ISSUE THREAD

**Issue by S0ulf3re** [nextcloud-snap/nextcloud-snap#2060]
I'm running a Nextcloud snap on Digitalocean and I'm trying to move my data folder to an encrypted volume. I tried to do it at setup but it completely ignored the changes I did to the config file before setting up my admin user. So I had to try again after setting up the user. So I followed the instructions [here](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Change-data-directory-to-use-another-disk-partition#if-you-have-already-created-an-admin-user) but after changing the config file it gave me an internal server error, so I tried changing the permissions again with ```sudo chown -R root:root /mnt/nextcloud``` and ```sudo chown -R root:root /mnt/nextcloud/data``` but that made things even worse because now redis isn't even working and it's only plain text instead of an html error. I'm running ubuntu 20.04.4 and the directory im using is /mnt/nextcloud/ with the data folder in there

Here is the [error.log](https://github.com/nextcloud-snap/nextcloud-snap/files/8598897/error.log) that I generated using the issue script

**Comment by S0ulf3re** [comment]
ok so I just tried running ```nextcloud.occ files:scan --all``` and this is what I got:


```
root@nextcloud-snap-instance:~# nextcloud.occ files:scan --all
Starting scan for user 1 out of 1 (soulfire)
Exception during scan: opendir(/mnt/nextcloud/data/soulfire/): Failed to open directory: Permission denied
#0 [internal function]: OCA\Files\Command\Scan->exceptionErrorHandler()
#1 /snap/nextcloud/30258/htdocs/lib/private/Files/Storage/Local.php(135): opendir()
#2 /snap/nextcloud/30258/htdocs/lib/private/Files/Storage/Common.php(879): OC\Files\Storage\Local->opendir()
#3 [internal function]: OC\Files\Storage\Common->getDirectoryContent()
#4 /snap/nextcloud/30258/htdocs/lib/private/Files/Cache/Scanner.php(410): iterator_to_array()
#5 /snap/nextcloud/30258/htdocs/lib/private/Files/Cache/Scanner.php(390): OC\Files\Cache\Scanner->handleChildren()
#6 /snap/nextcloud/30258/htdocs/lib/private/Files/Cache/Scanner.php(342): OC\Files\Cache\Scanner->scanChildren()
#7 /snap/nextcloud/30258/htdocs/lib/private/Files/Utils/Scanner.php(258): OC\Files\Cache\Scanner->scan()
#8 /snap/nextcloud/30258/htdocs/apps/files/lib/Command/Scan.php(143): OC\Files\Utils\Scanner->scan()
#9 /snap/nextcloud/30258/htdocs/apps/files/lib/Command/Scan.php(199): OCA\Files\Command\Scan->scanFiles()
#10 /snap/nextcloud/30258/htdocs/3rdparty/symfony/console/Command/Command.php(255): OCA\Files\Command\Scan->execute()
#11 /snap/nextcloud/30258/htdocs/core/Command/Base.php(168): Symfony\Component\Console\Command\Command->run()
#12 /snap/nextcloud/30258/htdocs/3rdparty/symfony/console/Application.php(1009): OC\Core\Command\Base->run()
#13 /snap/nextcloud/30258/htdocs/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#14 /snap/nextcloud/30258/htdocs/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#15 /snap/nextcloud/30258/htdocs/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#16 /snap/nextcloud/30258/htdocs/console.php(99): OC\Console\Application->run()
#17 /snap/nextcloud/30258/htdocs/occ(11): require_once('...')
#18 {main}
+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 1       | 0     | 00:00:00     |
+---------+-------+--------------+
root@nextcloud-snap-instance:~#
```

**Comment by S0ulf3re** [comment]
Managed to solve it by running ```snap connect nextcloud:removable-media``` as root
