### ISSUE TITLE
Suddendly, Snap NC stops working

### ISSUE THREAD

**Issue by EdG973GCS** [nextcloud-snap/nextcloud-snap#2231]
#### Describe the bug
I rebooted the linux server, then the web interface is not coming back (blank screen).

#### OS/snapd/snap version
$ sudo snap list
Name       Version      Rev    Tracking       Publisher   Notes
core18     20221027     2620   latest/stable  canonical✓  base
nextcloud  24.0.3snap1  31222  latest/stable  nextcloud✓  -
snapd      2.57.4       17336  latest/stable  canonical✓  snapd

and:

$ snap version
snap    2.56.2-4.fc36
snapd   2.56.2-4.fc36
series  16
fedora  36
kernel  6.0.5-200.fc36.x86_64
#### Logs
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).
[log_10112022.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/9981332/log_10112022.txt)

May you help me ?
Best Regards

**Comment by EdG973GCS** [comment]
The Snap NC Instance has passing in maintenance mode... I do not know why.

I disabled maintenance mode (off), and now I can get an "internal server error"

[log2_10112022.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/9982712/log2_10112022.txt)

![CaptureNC_Error](https://user-images.githubusercontent.com/105791599/201148360-992c66ca-ac66-4ae5-a3c7-0db0276e8d38.PNG)

And in command line, this is what I get :
$ sudo nextcloud.occ config:system:get trusted_domains

An unhandled exception has been thrown:
ParseError: syntax error, unexpected character 0x00, expecting ")" in /snap/nextcloud/31222/htdocs/apps/user_status/composer/composer/autoload_static.php:19
Stack trace:
#0 /snap/nextcloud/31222/htdocs/apps/user_status/composer/autoload.php(12): ComposerAutoloaderInitUserStatus::getLoader()
#1 /snap/nextcloud/31222/htdocs/lib/private/legacy/OC_App.php(284): require_once('...')
#2 /snap/nextcloud/31222/htdocs/lib/private/AppFramework/Bootstrap/Coordinator.php(117): OC_App::registerAutoloading()
#3 /snap/nextcloud/31222/htdocs/lib/private/AppFramework/Bootstrap/Coordinator.php(91): OC\AppFramework\Bootstrap\Coordinator->registerApps()
#4 /snap/nextcloud/31222/htdocs/lib/base.php(654): OC\AppFramework\Bootstrap\Coordinator->runInitialRegistration()
#5 /snap/nextcloud/31222/htdocs/lib/base.php(1104): OC::init()
#6 /snap/nextcloud/31222/htdocs/console.php(48): require_once('...')
#7 /snap/nextcloud/31222/htdocs/occ(11): require_once('...')

**Comment by EdG973GCS** [comment]
Allright, system upgrade in fedora 37 (kernel version is 6.0.7-301
Should be good enough for snaps compatibility

**Comment by EdG973GCS** [comment]
Done, fedora 37 upgrade ok 6.0.7-301
