### ISSUE TITLE
Lets-encrypt warning email

### ISSUE THREAD

**Issue by dln949** [nextcloud-snap/nextcloud-snap#2407]
Nextcloud 25.0.6snap1 installed on Ubuntu 22.04.  

I set this up a little over two months ago, so I'm completely new to all this let encrypt stuff.  

At the time I set this up, my understanding was that the Nextcloud snap installation would automatically handle the renewal of the lets encrypt certificate.  

But, today I got an email from lets encrypt saying that the certificate expires in 20 days and that I had better hurry and renew it.  

I don't know what to think of this.  

Is this completely normal, nothing is wrong, the Nextcloud snap package includes setup that will renew this lets encrypt certificate at the right time, and so I should just relax?  

Or, does the fact that lets encrypt sent me this email indicate that something is going wrong with my Nextcloud snap setup?  And if it does indicate that, how do I track down what is wrong, and fix whatever is wrong, and renew this lets encrypt certificate?  

Thanks in advance.

**Comment by scubamuc** [comment]
please show your LetsEncrypt log: 
`sudo cat /var/snap/nextcloud/current/certs/certbot/logs/letsencrypt.log`

[Nextcloud-snap LetsEncrypt](https://github.com/scubamuc/scubamuc.github.io/blob/scubamuc/wiki-md/NEXTCLOUD.snap--LetsEncrypt_wiki.md)

**Comment by dln949** [comment]
Output of sudo journalctl -u snap.nextcloud.renew-certs.service contains this:  

Apr 30 17:29:11 system59 nextcloud.renew-certs[1665768]: All renewal attempts failed. The following certs could not be renewed:
Apr 30 17:29:11 system59 nextcloud.renew-certs[1665768]:   /var/snap/nextcloud/current/certs/certbot/config/live/dln949.ddns.net/fullchain.pem (failure)
Apr 30 17:29:11 system59 nextcloud.renew-certs[1665768]: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Apr 30 17:29:11 system59 nextcloud.renew-certs[1665768]: Running post-hook command: restart-apache
Apr 30 17:29:12 system59 nextcloud.renew-certs[1665768]: Output from post-hook command restart-apache:
Apr 30 17:29:12 system59 nextcloud.renew-certs[1665768]: Restarting apache... done
Apr 30 17:29:12 system59 nextcloud.renew-certs[1665768]: 1 renew failure(s), 0 parse failure(s)
May 01 17:29:15 system59 nextcloud.renew-certs[1809150]: Saving debug log to /var/snap/nextcloud/current/certs/certbot/logs/letsencrypt.log
May 01 17:29:15 system59 nextcloud.renew-certs[1809150]: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
May 01 17:29:15 system59 nextcloud.renew-certs[1809150]: Processing
May 01 17:29:15 system59 nextcloud.renew-certs[1809150]: /var/snap/nextcloud/current/certs/certbot/config/renewal/dln949.ddns.net.conf
May 01 17:29:15 system59 nextcloud.renew-certs[1809150]: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
May 01 17:29:15 system59 nextcloud.renew-certs[1809150]: Cert is due for renewal, auto-renewing...
May 01 17:29:15 system59 nextcloud.renew-certs[1809150]: Non-interactive renewal: random delay of 262 seconds
May 01 17:33:37 system59 nextcloud.renew-certs[1809150]: Plugins selected: Authenticator webroot, Installer None
May 01 17:33:37 system59 nextcloud.renew-certs[1809150]: Renewing an existing certificate
May 01 17:33:39 system59 nextcloud.renew-certs[1809150]: Performing the following challenges:
May 01 17:33:39 system59 nextcloud.renew-certs[1809150]: http-01 challenge for dln949.ddns.net
May 01 17:33:39 system59 nextcloud.renew-certs[1809150]: Cleaning up challenges
May 01 17:33:39 system59 nextcloud.renew-certs[1809150]: Attempting to renew cert (dln949.ddns.net) from /var/snap/nextcloud/current/certs/certbot/config/renewal/dln949.ddns.net.conf produced an unexpected error: Missing command line flag or config entry for this setting:
May 01 17:33:39 system59 nextcloud.renew-certs[1809150]: Input the webroot for dln949.ddns.net:. Skipping.



The log you asked for:  

main59@system59:~$ sudo cat /var/snap/nextcloud/current/certs/certbot/logs/letsencrypt.log

[sudo] password for main59: 
2023-05-01 17:29:15,328:DEBUG:certbot.main:certbot version: 0.33.1
2023-05-01 17:29:15,329:DEBUG:certbot.main:Arguments: ['--text', '--config-dir', '/var/snap/nextcloud/current/certs/certbot/config', '--work-dir', '/var/snap/nextcloud/current/certs/certbot/work', '--logs-dir', '/var/snap/nextcloud/current/certs/certbot/logs', '--post-hook', 'restart-apache']
2023-05-01 17:29:15,329:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#nextcloud:webroot,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2023-05-01 17:29:15,369:DEBUG:certbot.log:Root logging level set at 20
2023-05-01 17:29:15,370:INFO:certbot.log:Saving debug log to /var/snap/nextcloud/current/certs/certbot/logs/letsencrypt.log
2023-05-01 17:29:15,534:DEBUG:certbot.plugins.selection:Requested authenticator <certbot.cli._Default object at 0x7fd4bfbf1850> and installer <certbot.cli._Default object at 0x7fd4bfbf1850>
2023-05-01 17:29:15,535:DEBUG:certbot.cli:Var config_dir=/var/snap/nextcloud/current/certs/certbot/config (set by user).
2023-05-01 17:29:15,535:DEBUG:certbot.cli:Var logs_dir=/var/snap/nextcloud/current/certs/certbot/logs (set by user).
2023-05-01 17:29:15,535:DEBUG:certbot.cli:Var work_dir=/var/snap/nextcloud/current/certs/certbot/work (set by user).
2023-05-01 17:29:15,602:DEBUG:certbot.storage:Should renew, less than 30 days before certificate expiry 2023-05-22 01:12:16 UTC.
2023-05-01 17:29:15,603:INFO:certbot.renewal:Cert is due for renewal, auto-renewing...
2023-05-01 17:29:15,603:INFO:certbot.renewal:Non-interactive renewal: random delay of 262 seconds
2023-05-01 17:33:37,697:DEBUG:certbot.plugins.selection:Requested authenticator webroot and installer None
2023-05-01 17:33:37,708:DEBUG:certbot.plugins.selection:Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot.plugins.webroot:Authenticator
Initialized: <certbot.plugins.webroot.Authenticator object at 0x7fd4bfde9b90>
Prep: True
2023-05-01 17:33:37,710:DEBUG:certbot.plugins.selection:Selected authenticator <certbot.plugins.webroot.Authenticator object at 0x7fd4bfde9b90> and installer None
2023-05-01 17:33:37,710:INFO:certbot.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2023-05-01 17:33:37,719:DEBUG:certbot.main:Picked account: <Account(RegistrationResource(body=Registration(status=None, terms_of_service_agreed=None, agreement=None, only_return_existing=None, contact=(), key=None, external_account_binding=None), uri=u'https://acme-v02.api.letsencrypt.org/acme/acct/974857996', new_authzr_uri=None, terms_of_service=None), 3d6f146c8853169acc50461f80d88f8c, Meta(creation_host=u'system59', creation_dt=datetime.datetime(2023, 2, 21, 1, 48, 12, tzinfo=<UTC>)))>
2023-05-01 17:33:37,722:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2023-05-01 17:33:37,730:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2023-05-01 17:33:37,906:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 756
2023-05-01 17:33:37,908:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 01 May 2023 22:33:37 GMT
Content-Type: application/json
Content-Length: 756
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "NcQ4O-KXoT0": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.3-September-21-2022.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "renewalInfo": "https://acme-v02.api.letsencrypt.org/get/draft-ietf-acme-ari-00/renewalInfo/",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2023-05-01 17:33:37,909:INFO:certbot.main:Renewing an existing certificate
2023-05-01 17:33:39,236:DEBUG:certbot.crypto_util:Generating key (4096 bits): /var/snap/nextcloud/current/certs/certbot/config/keys/0013_key-certbot.pem
2023-05-01 17:33:39,259:DEBUG:certbot.crypto_util:Creating CSR: /var/snap/nextcloud/current/certs/certbot/config/csr/0013_csr-certbot.pem
2023-05-01 17:33:39,260:DEBUG:acme.client:Requesting fresh nonce
2023-05-01 17:33:39,260:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2023-05-01 17:33:39,299:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2023-05-01 17:33:39,300:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 01 May 2023 22:33:39 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: C878QGaPFZJYR5MLxfp4-yJaybx6l_lqdsAWeXx66CigPuc
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2023-05-01 17:33:39,300:DEBUG:acme.client:Storing nonce: C878QGaPFZJYR5MLxfp4-yJaybx6l_lqdsAWeXx66CigPuc
2023-05-01 17:33:39,301:DEBUG:acme.client:JWS payload:
{
  "identifiers": [
    {
      "type": "dns", 
      "value": "dln949.ddns.net"
    }
  ]
}
2023-05-01 17:33:39,321:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJub25jZSI6ICJDODc4UUdhUEZaSllSNU1MeGZwNC15SmF5Yng2bF9scWRzQVdlWHg2NkNpZ1B1YyIsICJ1cmwiOiAiaHR0cHM6Ly9hY21lLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvbmV3LW9yZGVyIiwgImtpZCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hY2N0Lzk3NDg1Nzk5NiIsICJhbGciOiAiUlMyNTYifQ", 
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwgCiAgICAgICJ2YWx1ZSI6ICJkbG45NDkuZGRucy5uZXQiCiAgICB9CiAgXQp9", 
  "signature": "lDzoqwVKwWbkddoFKW2cxQ2RMZg0Ajz90JFXDq5U9HIzU8p66hHOggpE1CFWBEyitSVjX4NWYI96YWJBwmc27F5JvgVNJV7NQbYeHW3XCGKtWGDKCGaRSXn4aBU7LOo0n1I-gAIYY6O7JPYtgvKcr6vAtLnkW2a3PGVIKEGiktf_yNdZFD-3iHUNyutmMdTbblkQmmqGsdWq2EohQZAqfWZD7Y34ck-MEvPLci998DB8s7xhB0t7PQArcJgYwJCs2nMdxf-uh8wi2m74Ndw17orXEpR2QoTWNhJkdKzhI7CxZ_oCsA6DhqpBi055Vzlu9_Xm7-eL_2JntVm0WtnxC0_vZdne1QQHZHN3q7qA4JpCJcnrRpVpBKLptyl1pZkovXo22YZ8_lxbwOvCUscCHFyeykl49sVGszf2yNYhYGQaht81YHu2v3Qd0Rq6v4SBlO40Pwvj8R0RvQb5uZYmuNiZ4RyGZuNfgwdrDUgf4zCn6oc1QgPwmKSKvpjslQQl9rvEA-s-nA3V5POixQGg7hzlPCPi-4uST1hPfwiX4INUOLQhW0NVBUievEhXvGAkwl7VS8f0mbVEy-FrvI6ynk4i8tQsT_fGooWEMeYblPk9jCWS4U0jzViFhd9xEm2kqhnWIVzPwXbah3nxOjS5adw1DGHv9rwL3gSMdkuvHzk"
}
2023-05-01 17:33:39,375:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 340
2023-05-01 17:33:39,376:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Mon, 01 May 2023 22:33:39 GMT
Content-Type: application/json
Content-Length: 340
Connection: keep-alive
Boulder-Requester: 974857996
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/974857996/179181843327
Replay-Nonce: 1DFAAUrop_br6aGxqRN93tXWTvh-BicdhwH8Mp71hwh0GIg
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2023-05-06T22:25:55Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "dln949.ddns.net"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/223603487647"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/974857996/179181843327"
}
2023-05-01 17:33:39,377:DEBUG:acme.client:Storing nonce: 1DFAAUrop_br6aGxqRN93tXWTvh-BicdhwH8Mp71hwh0GIg
2023-05-01 17:33:39,377:DEBUG:acme.client:JWS payload:

2023-05-01 17:33:39,396:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/223603487647:
{
  "protected": "eyJub25jZSI6ICIxREZBQVVyb3BfYnI2YUd4cVJOOTN0WFdUdmgtQmljZGh3SDhNcDcxaHdoMEdJZyIsICJ1cmwiOiAiaHR0cHM6Ly9hY21lLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvYXV0aHotdjMvMjIzNjAzNDg3NjQ3IiwgImtpZCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hY2N0Lzk3NDg1Nzk5NiIsICJhbGciOiAiUlMyNTYifQ", 
  "payload": "", 
  "signature": "sHu-KecC1Qeb5e7m8KLUAFrf2xT3Zm9wbXjPw_sTOGgxke1Z-fI6IC_DgtBgTXpVR5ImlomKy6vWI8nuNuVNpRXjKjE1ycB9bDK1bxbWrCyIxH7BTu6H9g9h7t0lWnBSjTsvzGDmkyPIYwWHuFkNH3axKw7A6fR7kKyK5kBWtZCh40kkhzaOu8oA_LgCaYVmahH_dOgbnIy3a3gM_g2mbB22ULtHRpyUh_cCS3-ohaI-DacyEPoIji6mEha9uO7o-gQ3K2-B1frDW-zfDr4VKesMe0lj-l_rcQGtiBxvR6LdjS2FYIx3Ld05DKwcWe1TkOhuwzLwZgQjGB0BhKNW_uunD4aEwI24WL61Wb1Rbw1BqWed1qbL65t_T4qdrXfMyYNo4grVVewHo5Fbid203-ztSm1bCci-qc8mtLo5eX7ZnXuoUuOV7LcqasZ07vS30gANeOi-P7q44azsWwj1tI78cfuDOmyPx0_EnJT7bp9_Rqut6EcEDZGIB5RiyQdtoSIDGrtTmK5Q_w9UlkTX-Wl8gTFCmMyEhu4WCBgdliHpo3jy2FbcATtqph6QWgfvQrde4XK7BwsSHSXknTMx6eH5Ak4AZSC913kV808nxTB4eHsBLSKng3qmiE8gaSE-lhWWVdSE8lz2CRvv0VVj9q5kl_OCYg2Nwj7TGn1Otp4"
}
2023-05-01 17:33:39,439:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/223603487647 HTTP/1.1" 200 799
2023-05-01 17:33:39,440:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 01 May 2023 22:33:39 GMT
Content-Type: application/json
Content-Length: 799
Connection: keep-alive
Boulder-Requester: 974857996
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 1DFAFfKEpVOE0EYrA8sYTP3l4pYcI4HOUkpQNS_oplL8Ql8
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "dln949.ddns.net"
  },
  "status": "pending",
  "expires": "2023-05-06T22:25:55Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/223603487647/9nQJ5Q",
      "token": "cRw6x6Vf7mnTOKK9Ob-XcGSpjKflMEOzoFOZdLYIFUw"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/223603487647/PwLCXw",
      "token": "cRw6x6Vf7mnTOKK9Ob-XcGSpjKflMEOzoFOZdLYIFUw"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/223603487647/VQEHcg",
      "token": "cRw6x6Vf7mnTOKK9Ob-XcGSpjKflMEOzoFOZdLYIFUw"
    }
  ]
}
2023-05-01 17:33:39,441:DEBUG:acme.client:Storing nonce: 1DFAFfKEpVOE0EYrA8sYTP3l4pYcI4HOUkpQNS_oplL8Ql8
2023-05-01 17:33:39,442:INFO:certbot.auth_handler:Performing the following challenges:
2023-05-01 17:33:39,442:INFO:certbot.auth_handler:http-01 challenge for dln949.ddns.net
2023-05-01 17:33:39,444:DEBUG:certbot.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/snap/nextcloud/34542/lib/python2.7/site-packages/certbot/auth_handler.py", line 69, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/snap/nextcloud/34542/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 81, in perform
    self._set_webroots(achalls)
  File "/snap/nextcloud/34542/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 99, in _set_webroots
    known_webroots)
  File "/snap/nextcloud/34542/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 120, in _prompt_for_webroot
    webroot = self._prompt_for_new_webroot(domain, True)
  File "/snap/nextcloud/34542/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 144, in _prompt_for_new_webroot
    force_interactive=True)
  File "/snap/nextcloud/34542/lib/python2.7/site-packages/certbot/display/ops.py", line 371, in validated_directory
    validator, *args, **kwargs)
  File "/snap/nextcloud/34542/lib/python2.7/site-packages/certbot/display/ops.py", line 328, in _get_validated
    code, raw = method(message, default=default, **kwargs)
  File "/snap/nextcloud/34542/lib/python2.7/site-packages/certbot/display/util.py", line 583, in directory_select
    return self.input(message, default, cli_flag)
  File "/snap/nextcloud/34542/lib/python2.7/site-packages/certbot/display/util.py", line 524, in input
    self._interaction_fail(message, cli_flag)
  File "/snap/nextcloud/34542/lib/python2.7/site-packages/certbot/display/util.py", line 469, in _interaction_fail
    raise errors.MissingCommandlineFlag(msg)
MissingCommandlineFlag: Missing command line flag or config entry for this setting:
Input the webroot for dln949.ddns.net:

2023-05-01 17:33:39,444:DEBUG:certbot.error_handler:Calling registered functions
2023-05-01 17:33:39,445:INFO:certbot.auth_handler:Cleaning up challenges
2023-05-01 17:33:39,445:DEBUG:certbot.plugins.webroot:All challenges cleaned up
2023-05-01 17:33:39,445:WARNING:certbot.renewal:Attempting to renew cert (dln949.ddns.net) from /var/snap/nextcloud/current/certs/certbot/config/renewal/dln949.ddns.net.conf produced an unexpected error: Missing command line flag or config entry for this setting:
Input the webroot for dln949.ddns.net:. Skipping.
2023-05-01 17:33:39,447:DEBUG:certbot.renewal:Traceback was:
Traceback (most recent call last):
  File "/snap/nextcloud/34542/lib/python2.7/site-packages/certbot/renewal.py", line 450, in handle_renewal_request
    main.renew_cert(lineage_config, plugins, renewal_candidate)
  File "/snap/nextcloud/34542/lib/python2.7/site-packages/certbot/main.py", line 1192, in renew_cert
    renewed_lineage = _get_and_save_cert(le_client, config, lineage=lineage)
  File "/snap/nextcloud/34542/lib/python2.7/site-packages/certbot/main.py", line 115, in _get_and_save_cert
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/snap/nextcloud/34542/lib/python2.7/site-packages/certbot/renewal.py", line 308, in renew_cert
    new_cert, new_chain, new_key, _ = le_client.obtain_certificate(domains, new_key)
  File "/snap/nextcloud/34542/lib/python2.7/site-packages/certbot/client.py", line 349, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/snap/nextcloud/34542/lib/python2.7/site-packages/certbot/client.py", line 385, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/snap/nextcloud/34542/lib/python2.7/site-packages/certbot/auth_handler.py", line 69, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/snap/nextcloud/34542/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 81, in perform
    self._set_webroots(achalls)
  File "/snap/nextcloud/34542/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 99, in _set_webroots
    known_webroots)
  File "/snap/nextcloud/34542/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 120, in _prompt_for_webroot
    webroot = self._prompt_for_new_webroot(domain, True)
  File "/snap/nextcloud/34542/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 144, in _prompt_for_new_webroot
    force_interactive=True)
  File "/snap/nextcloud/34542/lib/python2.7/site-packages/certbot/display/ops.py", line 371, in validated_directory
    validator, *args, **kwargs)
  File "/snap/nextcloud/34542/lib/python2.7/site-packages/certbot/display/ops.py", line 328, in _get_validated
    code, raw = method(message, default=default, **kwargs)
  File "/snap/nextcloud/34542/lib/python2.7/site-packages/certbot/display/util.py", line 583, in directory_select
    return self.input(message, default, cli_flag)
  File "/snap/nextcloud/34542/lib/python2.7/site-packages/certbot/display/util.py", line 524, in input
    self._interaction_fail(message, cli_flag)
  File "/snap/nextcloud/34542/lib/python2.7/site-packages/certbot/display/util.py", line 469, in _interaction_fail
    raise errors.MissingCommandlineFlag(msg)
MissingCommandlineFlag: Missing command line flag or config entry for this setting:
Input the webroot for dln949.ddns.net:

2023-05-01 17:33:39,447:ERROR:certbot.renewal:All renewal attempts failed. The following certs could not be renewed:
2023-05-01 17:33:39,447:ERROR:certbot.renewal:  /var/snap/nextcloud/current/certs/certbot/config/live/dln949.ddns.net/fullchain.pem (failure)
2023-05-01 17:33:39,449:INFO:certbot.hooks:Running post-hook command: restart-apache
2023-05-01 17:33:40,672:INFO:certbot.hooks:Output from post-hook command restart-apache:
Restarting apache... done

2023-05-01 17:33:40,673:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/snap/nextcloud/34542/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/snap/nextcloud/34542/lib/python2.7/site-packages/certbot/main.py", line 1364, in main
    return config.func(config, plugins)
  File "/snap/nextcloud/34542/lib/python2.7/site-packages/certbot/main.py", line 1271, in renew
    renewal.handle_renewal_request(config)
  File "/snap/nextcloud/34542/lib/python2.7/site-packages/certbot/renewal.py", line 475, in handle_renewal_request
    len(renew_failures), len(parse_failures)))
Error: 1 renew failure(s), 0 parse failure(s)
main59@system59:~$

**Comment by kyrofa** [comment]
Looks like the webroot. @dln949 can I see the contents of `/var/snap/nextcloud/current/certs/certbot/config/renewal/dln949.ddns.net.conf`, please (I may not have that file named properly, but it should be obvious)? Mask out your account like `account = <account>`, we don't need to see that; the rest is safely made public.

**Comment by kyrofa** [comment]
Huh, that is indeed missing the webroot map, I wonder how that got garbled. Easy to fix, though! Make the end of that file, the `[[webroot_map]]` stuff, look like this:


```
[[webroot_map]]
dln949.ddns.net = /var/snap/nextcloud/current/certs/certbot
www.dln949.ddns.net = /var/snap/nextcloud/current/certs/certbot
```

**Comment by dln949** [comment]
Here is the output, after about three minutes it seems just hanging at this point, I don't know if this is all the output to expect or if there is something wrong - nor do I know what the output is telling me, it says the certificate is not yet due for renewal, but per Lets Encrypt's email it will need renewal in 19 days:  

main59@system59:~$ sudo snap restart nextcloud.renew-certs && sudo snap logs -f nextcloud.renew-certs
[sudo] password for main59: 
Restarted.
2023-05-02T12:40:35-05:00 nextcloud.renew-certs[10929]: Processing
2023-05-02T12:40:35-05:00 nextcloud.renew-certs[10929]: /var/snap/nextcloud/current/certs/certbot/config/renewal/dln949.ddns.net.conf
2023-05-02T12:40:35-05:00 nextcloud.renew-certs[10929]: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2023-05-02T12:40:35-05:00 nextcloud.renew-certs[10929]: Cert not yet due for renewal
2023-05-02T12:40:35-05:00 nextcloud.renew-certs[10929]: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2023-05-02T12:40:35-05:00 nextcloud.renew-certs[10929]: The following certs are not due for renewal yet:
2023-05-02T12:40:35-05:00 nextcloud.renew-certs[10929]:   /var/snap/nextcloud/current/certs/certbot/config/live/dln949.ddns.net/fullchain.pem expires on 2023-07-31 (skipped)
2023-05-02T12:40:35-05:00 nextcloud.renew-certs[10929]: No renewals were attempted.
2023-05-02T12:40:35-05:00 nextcloud.renew-certs[10929]: No hooks were run.
2023-05-02T12:40:35-05:00 nextcloud.renew-certs[10929]: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by scubamuc** [comment]
@dln949 success, looks like you renewed your certificate:
![grafik](https://user-images.githubusercontent.com/54933878/235766864-e6635fba-ea8e-458c-91c6-40ce82265412.png)

**Comment by kyrofa** [comment]
Agreed, looks like you're good now.

**Comment by dln949** [comment]
Thanks much to all.
