### ISSUE TITLE
made a boo-bo

### ISSUE THREAD

**Issue by mattish91** [nextcloud-snap/nextcloud-snap#2653]
#### Describe the bug
Got some issues  with  sign in and figured out that this might be an issue with my proxy changing ip since a week ago.  The setup was how  ever  working untill  yesterday, but figured it wouldn't hurt to  set the correct  trusted proxy anyways.

Simply forgot to  add `--value=` to my command and now i can't fix the issue i just made up 😂

#### To Reproduce
1. Do not ssh in to your to take a snapshot before you make any changes YOLO
2. SSH in to your server,  make sure you `sudo su`, type `nextcloud .occ config:system:set trusted_proxies => 2 #Proxy_IP`
3. Check the configuration by typing `nextcloud.occ config:system:get trusted_proxies`

#### Expected behavior
Most likely a error that wouldn't let me apply my messed up command telling me im missing the value variable xD

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud
    nextcloud  27.1.4snap1  39212  latest/stable  nextcloud✓  -

and:

    $ snap version
    snap    2.61.1
    snapd   2.61.1
    series  16
    ubuntu  22.04
    kernel  5.15.0-91-generic

#### Logs
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).

Pastebin: https://pastebin.com/8PYsDqCp

#### Error:  

root@nextcloud:/home/master# `nextcloud.occ config:system:get trusted_proxies`
An unhandled exception has been thrown:
TypeError: Symfony\Component\HttpFoundation\IpUtils::checkIp4(): Argument #2 ($ip) must be of type string, array given, called in /snap/nextcloud/39212/htdocs/3rdparty/symfony/http-foundation/IpUtils.php on line 52 and defined in /snap/nextcloud/39212/htdocs/3rdparty/symfony/http-foundation/IpUtils.php:68
Stack trace:
#0 /snap/nextcloud/39212/htdocs/3rdparty/symfony/http-foundation/IpUtils.php(52): Symfony\Component\HttpFoundation\IpUtils::checkIp4()
#1 /snap/nextcloud/39212/htdocs/lib/private/AppFramework/Http/Request.php(580): Symfony\Component\HttpFoundation\IpUtils::checkIp()
#2 /snap/nextcloud/39212/htdocs/lib/private/AppFramework/Http/Request.php(878): OC\AppFramework\Http\Request->isTrustedProxy()
#3 /snap/nextcloud/39212/htdocs/lib/private/AppFramework/Http/Request.php(806): OC\AppFramework\Http\Request->fromTrustedProxy()
#4 /snap/nextcloud/39212/htdocs/lib/private/AppFramework/Http/Request.php(843): OC\AppFramework\Http\Request->getInsecureServerHost()
#5 /snap/nextcloud/39212/htdocs/lib/private/Route/Router.php(93): OC\AppFramework\Http\Request->getServerHost()
#6 /snap/nextcloud/39212/htdocs/lib/private/Route/CachingRouter.php(47): OC\Route\Router->__construct()
#7 [internal function]: OC\Route\CachingRouter->__construct()
#8 /snap/nextcloud/39212/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(116): ReflectionClass->newInstanceArgs()
#9 /snap/nextcloud/39212/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(124): OC\AppFramework\Utility\SimpleContainer->buildClass()
#10 /snap/nextcloud/39212/htdocs/lib/private/Server.php(836): OC\AppFramework\Utility\SimpleContainer->resolve()
#11 /snap/nextcloud/39212/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(171): OC\Server->OC\{closure}()
#12 /snap/nextcloud/39212/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#13 /snap/nextcloud/39212/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet()
#14 /snap/nextcloud/39212/htdocs/lib/private/ServerContainer.php(171): OC\AppFramework\Utility\SimpleContainer->query()
#15 /snap/nextcloud/39212/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(97): OC\ServerContainer->query()
#16 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#17 /snap/nextcloud/39212/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(116): array_map()
#18 /snap/nextcloud/39212/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(124): OC\AppFramework\Utility\SimpleContainer->buildClass()
#19 /snap/nextcloud/39212/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(142): OC\AppFramework\Utility\SimpleContainer->resolve()
#20 /snap/nextcloud/39212/htdocs/lib/private/ServerContainer.php(171): OC\AppFramework\Utility\SimpleContainer->query()
#21 /snap/nextcloud/39212/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(65): OC\ServerContainer->query()
#22 /snap/nextcloud/39212/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(193): OC\AppFramework\Utility\SimpleContainer->get()
#23 /snap/nextcloud/39212/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(171): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#24 /snap/nextcloud/39212/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#25 /snap/nextcloud/39212/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet()
#26 /snap/nextcloud/39212/htdocs/lib/private/ServerContainer.php(171): OC\AppFramework\Utility\SimpleContainer->query()
#27 /snap/nextcloud/39212/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(97): OC\ServerContainer->query()
#28 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#29 /snap/nextcloud/39212/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(116): array_map()
#30 /snap/nextcloud/39212/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(124): OC\AppFramework\Utility\SimpleContainer->buildClass()
#31 /snap/nextcloud/39212/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(142): OC\AppFramework\Utility\SimpleContainer->resolve()
#32 /snap/nextcloud/39212/htdocs/lib/private/ServerContainer.php(171): OC\AppFramework\Utility\SimpleContainer->query()
#33 /snap/nextcloud/39212/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(65): OC\ServerContainer->query()
#34 /snap/nextcloud/39212/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(193): OC\AppFramework\Utility\SimpleContainer->get()
#35 /snap/nextcloud/39212/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(171): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#36 /snap/nextcloud/39212/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#37 /snap/nextcloud/39212/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet()
#38 /snap/nextcloud/39212/htdocs/lib/private/ServerContainer.php(171): OC\AppFramework\Utility\SimpleContainer->query()
#39 /snap/nextcloud/39212/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(65): OC\ServerContainer->query()
#40 /snap/nextcloud/39212/htdocs/lib/private/App/AppManager.php(461): OC\AppFramework\Utility\SimpleContainer->get()
#41 /snap/nextcloud/39212/htdocs/lib/private/legacy/OC_App.php(137): OC\App\AppManager->loadApp()
#42 /snap/nextcloud/39212/htdocs/lib/base.php(787): OC_App::loadApp()
#43 /snap/nextcloud/39212/htdocs/lib/base.php(1196): OC::init()
#44 /snap/nextcloud/39212/htdocs/console.php(48): require_once('...')
#45 /snap/nextcloud/39212/htdocs/occ(11): require_once('...')

Next try will  be to make a repair, not sure if that's going to  help but i obviously messed up the  config.php 😂

If anyone have any idea of what i could do or  try to do in order to fix  this, anything is welcome 😂

**Comment by mattish91** [comment]
Never mind, `nano /var/snap/nextcloud/current/nextcloud/config/config.php`

Gave me 
```
$CONFIG = array (
    'trusted_proxies' =>
     array (
        0 => '#Proxy_IP1',
        1 => '#Proxy_IP2',
        array (
            '=',
            '#Proxy_IP3',
        ),
    ),   
```

So i just had to remove this part and it worked flawlessly after that:
```
array (
            '=',
            '#Proxy_IP3',
        ),
```
